---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-calico-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-calico-controller
  namespace: kube-system
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-calico-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-calico-controller
subjects:
- kind: ServiceAccount
  name: kube-calico-controller
  namespace: kube-system

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-calico-controller
  namespace: kube-system
  labels:
    k8s-app: kube-calico-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kube-calico-controller
  template:
    metadata:
      labels:
        k8s-app: kube-calico-controller
      annotations:
        # For 1.6, we keep the old tolerations in case of a downgrade to 1.5
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated", "value":"master"}]'
    spec:
      containers:
        - image: ottoyiu/kube-calico-controller:0.0.3
          name: kube-calico-controller
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
          env:
          - name: ETCD_ENDPOINTS
            valueFrom:
              configMapKeyRef:
                key: etcd_endpoints
                name: calico-config
          volumeMounts:
            - name: ssl-certs
              mountPath: "/etc/ssl/certs/ca-certificates.crt"
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
